macro(custom_platform_include_if_exists file)
  if("${PLATFORM}" MATCHES "Custom")
    if (EXISTS "${PLATFORM_CUSTOM_ROOT_DIR}/cmake/${file}.cmake")
      include("${PLATFORM_CUSTOM_ROOT_DIR}/cmake/${file}.cmake")
    else ()
      message(STATUS "No file ${PLATFORM_CUSTOM_ROOT_DIR}/cmake/${file}.cmake detected... skipped")
    endif ()
  endif()
endmacro()
